import Navbar from "./components/navbar";
import Footer from "./components/footer";
import "./globals.css";

export const metadata = {
  title: "React blog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex flex-column justify-start item-center bg-[#f5f5f5]">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}