import { lora, noto_serif_kr} from "./fonts";
import Navbar from "./components/Navbar";
import "./globals.css";

export const metadata = {
  title: "React blog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${noto_serif_kr.variable} ${lora.variable}`}>
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
