import { lora, noto_serif_kr} from "./fonts";
import Navbar from "./components/navbar";
import Footer from "./components/footer";
import "./globals.css";

export const metadata = {
  title: "React blog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${noto_serif_kr.variable} ${lora.variable}`}>
      <body className="flex flex-column justify-start item-center">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
